name: docs

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # Repository
      - name: Checkout the code
        uses: actions/checkout@v4

      # Environment
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      # Docs
      - name: Build docs
        run: |
          cd docs
          uv run make html

      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/build/html/

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/dev'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
