name: lint

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # Repository
      - name: Checkout the code
        uses: actions/checkout@v4

      # Environment
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      # Lint
      - name: Lint
        run: |
          uv run ./lint.sh
