name: test

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # Repository
      - name: Checkout the code
        uses: actions/checkout@v4

      # Environment
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      # Test
      - name: Test
        run: |
          uv run pytest -n auto -v automol
          uv run pytest -v autochem
          uv run pytest -v autoreact
